# Generated by Django 5.2.1 on 2025-05-30 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bike_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=10)),
                ('km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='travel_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('starting_point', models.CharField(max_length=255)),
                ('ending_point', models.CharField(max_length=255)),
                ('date_range', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('km', models.IntegerField()),
                ('number_of_persons', models.PositiveIntegerField()),
                ('joined_members', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_notes', models.TextField()),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biker.travel_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Joined_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travelplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_entries', to='biker.travel_plan')),
            ],
        ),
    ]
